import type {
  AdminActivity,
  AdminAnalyticsTab,
  AdminComboChartPoint,
  AdminNeedsAttentionItem,
  AdminOverviewKpi,
  AdminAuction,
  AdminAuditEntry,
  AdminBuyer,
  AdminFee,
  AdminHistoryItem,
  AdminLot,
  AdminNote,
  AdminOrder,
  AdminPriorityItem,
  AdminProxyBid,
  AdminQueueCard,
  AdminReferral,
  AdminRegulation,
  AdminSettlement,
  AdminShipment,
  AdminSyncJob,
  AdminTicket,
  AdminTier,
  AdminTplCheck,
  AdminTransaction,
  AdminUserRecord,
  AdminVerification,
  AdminWithdrawal,
} from '@/types/admin'

const note = (id: string, body: string, at: string): AdminNote => ({
  id,
  body,
  at,
  author: 'Ops Admin',
})

const hist = (title: string, at: string, status: string, detail?: string): AdminHistoryItem => ({
  title,
  at,
  status,
  detail,
})

export const ADMIN_OVERVIEW_KPIS: AdminOverviewKpi[] = [
  { label: 'Buyers', value: '8' },
  { label: 'KYC pending', value: '3', hint: 'Needs review', hintTone: 'warning' },
  { label: 'Live auctions', value: '2', dot: 'maroon' },
  { label: 'Settlements due', value: '3', hint: 'Next 12h window', hintTone: 'warning' },
  { label: 'Deposits today', value: '$42,300' },
  { label: 'Withdrawals pending', value: '2' },
  { label: 'Placement queue', value: '2' },
  { label: 'Fees today', value: '$3,150' },
]

export const ADMIN_NEEDS_ATTENTION: AdminNeedsAttentionItem[] = [
  {
    id: 'na1',
    category: 'Settlement',
    detail: 'Ada Okonkwo · $1,840 · 2h 14m',
    to: '/admin/settlements/SET-8821',
  },
  {
    id: 'na2',
    category: 'Placement',
    detail: 'Lot #8821 · T-30 in 45m',
    to: '/admin/proxy-placement/PRX-8821',
  },
  {
    id: 'na3',
    category: 'Withdrawal',
    detail: 'Chidi Madueke · $500',
    to: '/admin/withdrawals/WDR-331',
  },
]

export const ADMIN_DEPOSITS_BIDS_CHART: AdminComboChartPoint[] = [
  { label: 'Mon', deposits: 30, bids: 22 },
  { label: 'Tue', deposits: 73, bids: 55 },
  { label: 'Wed', deposits: 44, bids: 38 },
  { label: 'Thur', deposits: 72, bids: 60 },
  { label: 'Fri', deposits: 77, bids: 68 },
  { label: 'Sat', deposits: 73, bids: 50 },
  { label: 'Sun', deposits: 51, bids: 35 },
]

export const ADMIN_QUEUE_CARDS: AdminQueueCard[] = [
  {
    id: 'verification',
    title: 'Verification',
    count: 3,
    description: 'Buyers waiting for KYC/KYB review.',
    to: '/admin/verification',
    icon: 'verification',
    tone: 'maroon',
  },
  {
    id: 'settlements',
    title: 'Settlements · 12h',
    count: 3,
    description: 'Auction winners with remaining balance due.',
    to: '/admin/settlements',
    icon: 'settlements',
    tone: 'amber',
  },
  {
    id: 'proxy',
    title: 'Proxy Placement',
    count: 2,
    description: 'BidBridge winners requiring B-Stock placement.',
    to: '/admin/proxy-placement',
    icon: 'proxy',
    tone: 'maroon',
  },
  {
    id: 'withdrawals',
    title: 'Withdrawals',
    count: 2,
    description: 'Buyers requesting payout from wallet.',
    to: '/admin/withdrawals',
    icon: 'withdrawals',
    tone: 'maroon',
  },
  {
    id: 'tpl',
    title: '3PL Verification',
    count: 3,
    description: 'Orders requiring IMEI/serial number checks.',
    to: '/admin/3pl-verification',
    icon: 'tpl',
    tone: 'amber',
  },
  {
    id: 'support',
    title: 'Support',
    count: 3,
    description: 'Tickets approaching or past SLA.',
    to: '/admin/support',
    icon: 'support',
    tone: 'amber',
  },
]

export const ADMIN_PRIORITY: AdminPriorityItem[] = [
  {
    id: 'p1',
    label: 'SETTLEMENT · OVERDUE',
    title: 'Bola Shittu · $410',
    detail: 'Gaming console lot #3312 · 12h window expired',
    tone: 'urgent',
    to: '/admin/settlements/SET-3312',
  },
  {
    id: 'p2',
    label: 'SUPPORT · SLA BREACHED',
    title: 'Bola Shittu',
    detail: 'Settlement window expired unfairly',
    tone: 'urgent',
    to: '/admin/support/TCK-2041',
  },
  {
    id: 'p3',
    label: '3PL VERIFICATION · FAILED',
    title: 'Amaka Eze · ORD-810',
    detail: 'Phonecheck reported device blacklisted',
    tone: 'urgent',
    to: '/admin/3pl-verification/TPL-810',
  },
  {
    id: 'p4',
    label: 'PROXY PLACEMENT · T-30',
    title: 'Lot #8821 · Ada Okonkwo',
    detail: 'T-30 window in 45m',
    tone: 'approaching',
    to: '/admin/proxy-placement/PRX-8821',
  },
  {
    id: 'p5',
    label: 'WITHDRAWAL · PENDING',
    title: 'Chidi Madueke · $500',
    detail: 'Requested 16 Aug 2026',
    tone: 'approaching',
    to: '/admin/withdrawals/WDR-331',
  },
  {
    id: 'p6',
    label: 'VERIFICATION · PENDING',
    title: 'Ngozi Balogun',
    detail: 'Business KYB · submitted 17 Aug',
    tone: 'approaching',
    to: '/admin/verification/VER-104',
  },
]

export const ADMIN_ACTIVITY: AdminActivity[] = [
  { id: 'a1', activity: 'Buyer tier overridden', reference: 'Ada Okonkwo', status: 'Tier 2', at: '17 Aug · 14:10' },
  { id: 'a2', activity: 'KYC verification approved', reference: 'Emeka Terver', status: 'Approved', at: '17 Aug · 08:31' },
  { id: 'a3', activity: 'Settlement marked default', reference: 'Bola Shittu · lot #3312', status: 'Default', at: '16 Aug · 09:44' },
  { id: 'a4', activity: '3PL verification failed', reference: 'ORD-810 · Amaka Eze', status: 'Failed', at: '15 Aug · 09:12' },
  { id: 'a5', activity: 'Verified at US 3PL', reference: 'ORD-655 · F. Adeyemi', status: 'Verified', at: '12 Aug · 08:10' },
  { id: 'a6', activity: 'Withdrawal approved', reference: 'WDR-322 · Ada Okonkwo', status: 'Approved', at: '10 Aug · 09:15' },
]

export const ADMIN_VERIFICATIONS: AdminVerification[] = [
  {
    id: 'VER-104',
    applicant: 'Ngozi Balogun',
    accountType: 'Business',
    verificationType: 'Business KYB',
    submitted: '17 Aug 2026',
    lastUpdated: '17 Aug 2026',
    status: 'Pending',
    email: 'ngozi.balogun@example.com',
    phone: '+234 802 114 5567',
    address: '14 Adeola Odeku St, Lagos',
    businessName: 'Balogun Trading Co.',
    registrationNo: 'RC-4471829',
    reviewedBy: 'Not yet reviewed',
    documents: [
      { name: 'Certificate of Incorporation (CAC).pdf', size: '1.2 MB', uploaded: '17 Aug 2026, 08:30', status: 'Pending' },
      { name: 'Director’s National ID.jpg', size: '840 KB', uploaded: '17 Aug 2026, 08:30', status: 'Pending' },
      { name: 'Proof of Business Address.pdf', size: '2.1 MB', uploaded: '17 Aug 2026, 08:31', status: 'Pending' },
    ],
    history: [
      hist('Verification Submitted', '17 Aug 2026, 08:30', 'Completed', 'Applicant submitted Business KYB documents'),
      hist('Documents Received', '17 Aug 2026, 08:31', 'Completed', '3 documents uploaded and queued for review'),
      hist('Pending Review', '17 Aug 2026, 08:31', 'Pending', 'Awaiting admin verification'),
    ],
    notes: [],
  },
  {
    id: 'VER-103',
    applicant: 'Ifeoma Nwosu',
    accountType: 'Individual',
    verificationType: 'Individual KYC',
    submitted: '16 Aug 2026',
    lastUpdated: '16 Aug 2026',
    status: 'Rejected',
    email: 'ifeoma.nwosu@example.com',
    phone: '+234 803 441 2290',
    address: '8 Admiralty Way, Lekki',
    reviewedBy: 'Ops Admin',
    documents: [{ name: 'National ID.jpg', size: '620 KB', uploaded: '16 Aug 2026, 11:04', status: 'Rejected' }],
    history: [
      hist('Verification Submitted', '16 Aug 2026, 11:02', 'Completed'),
      hist('Rejected', '16 Aug 2026, 16:40', 'Rejected', 'ID document unreadable'),
    ],
    notes: [note('n1', 'Photo is cropped and glare covers the ID number.', '16 Aug 2026, 16:38')],
  },
  {
    id: 'VER-102',
    applicant: 'Bola Shittu',
    accountType: 'Individual',
    verificationType: 'Individual KYC',
    submitted: '15 Aug 2026',
    lastUpdated: '15 Aug 2026',
    status: 'Pending',
    email: 'bola.shittu@example.com',
    phone: '+234 809 112 8844',
    address: '21 Allen Avenue, Ikeja',
    reviewedBy: 'Not yet reviewed',
    documents: [{ name: 'Passport.pdf', size: '1.1 MB', uploaded: '15 Aug 2026, 09:18', status: 'Pending' }],
    history: [hist('Verification Submitted', '15 Aug 2026, 09:18', 'Completed'), hist('Pending Review', '15 Aug 2026, 09:18', 'Pending')],
    notes: [],
  },
  {
    id: 'VER-090',
    applicant: 'Tunde Bakare',
    accountType: 'Individual',
    verificationType: 'Individual KYC',
    submitted: '10 Feb 2026',
    lastUpdated: '12 Feb 2026',
    status: 'Requires Resubmission',
    email: 'tunde.bakare@example.com',
    phone: '+234 701 334 0091',
    address: '5 Ribadu Road, Ikoyi',
    reviewedBy: 'Ops Admin',
    documents: [{ name: 'Utility bill.pdf', size: '400 KB', uploaded: '10 Feb 2026', status: 'Requires Resubmission' }],
    history: [
      hist('Verification Submitted', '10 Feb 2026, 10:00', 'Completed'),
      hist('Resubmission requested', '12 Feb 2026, 14:22', 'Requires Resubmission', 'Address proof older than 3 months'),
    ],
    notes: [],
  },
  {
    id: 'VER-044',
    applicant: 'Ada Okonkwo',
    accountType: 'Individual',
    verificationType: 'Individual KYC',
    submitted: '2 Jun 2026',
    lastUpdated: '3 Jun 2026',
    status: 'Approved',
    email: 'ada.okonkwo@example.com',
    phone: '+234 802 555 0192',
    address: '19 Bourdillon Road, Ikoyi',
    reviewedBy: 'Ops Admin',
    documents: [{ name: 'National ID.jpg', size: '910 KB', uploaded: '2 Jun 2026', status: 'Approved' }],
    history: [hist('Verification Submitted', '2 Jun 2026, 09:00', 'Completed'), hist('Approved', '3 Jun 2026, 11:14', 'Approved')],
    notes: [],
  },
  {
    id: 'VER-041',
    applicant: 'Chidi Madueke',
    accountType: 'Individual',
    verificationType: 'Individual KYC',
    submitted: '1 Mar 2026',
    lastUpdated: '2 Mar 2026',
    status: 'Approved',
    email: 'chidi.madueke@example.com',
    phone: '+234 803 221 6677',
    address: '44 Awolowo Road, Ikoyi',
    reviewedBy: 'Ops Admin',
    documents: [{ name: 'Passport.pdf', size: '1.4 MB', uploaded: '1 Mar 2026', status: 'Approved' }],
    history: [hist('Approved', '2 Mar 2026, 08:40', 'Approved')],
    notes: [],
  },
]

export const ADMIN_SETTLEMENTS: AdminSettlement[] = [
  {
    id: 'SET-3312',
    buyer: 'Bola Shittu',
    lot: 'Gaming console lot #3312',
    amount: '$1,840',
    remaining: '$410',
    window: 'Expired',
    status: 'Overdue',
    due: '16 Aug 2026, 09:30',
    wonAt: '15 Aug 2026, 21:30',
    method: 'Wallet + card',
    orderRef: 'ORD-3312',
    fees: '$46',
    netAmount: '$1,794',
    date: '15 Aug 2026',
    history: [hist('Won auction', '15 Aug 2026, 21:30', 'Completed'), hist('12h window expired', '16 Aug 2026, 09:30', 'Overdue')],
    notes: [],
  },
  {
    id: 'SET-8821',
    buyer: 'Ada Okonkwo',
    lot: 'Lot #8821 — mixed pallet',
    amount: '$2,400',
    remaining: '$600',
    window: '2h 14m',
    status: 'Pending',
    due: '17 Aug 2026, 16:40',
    wonAt: '17 Aug 2026, 04:40',
    method: 'Wallet',
    orderRef: 'ORD-992',
    fees: '$60',
    netAmount: '$2,340',
    date: '17 Aug 2026',
    history: [hist('Won auction', '17 Aug 2026, 04:40', 'Completed')],
    notes: [],
  },
  {
    id: 'SET-4410',
    buyer: 'Emeka Terver',
    lot: 'Electronics pallet #4410',
    amount: '$980',
    remaining: '$0',
    window: '—',
    status: 'Completed',
    due: '12 Aug 2026, 18:00',
    wonAt: '12 Aug 2026, 06:00',
    method: 'Wallet',
    orderRef: 'ORD-4410',
    fees: '$25',
    netAmount: '$955',
    date: '12 Aug 2026',
    history: [hist('Settled in full', '12 Aug 2026, 11:20', 'Completed')],
    notes: [],
  },
  {
    id: 'SET-2201',
    buyer: 'Funmi Adeyemi',
    lot: 'CBD case lot #2201',
    amount: '$1,120',
    remaining: '$1,120',
    window: 'On hold',
    status: 'On Hold',
    due: '18 Aug 2026, 10:00',
    wonAt: '17 Aug 2026, 22:00',
    method: 'Wire',
    orderRef: 'AUC-2201',
    fees: '$28',
    netAmount: '$1,092',
    date: '17 Aug 2026',
    history: [hist('Placed on hold', '17 Aug 2026, 22:40', 'On Hold', 'Awaiting wire confirmation')],
    notes: [],
  },
]

export const ADMIN_PROXIES: AdminProxyBid[] = [
  {
    id: 'PRX-8821',
    lot: 'Lot #8821',
    buyer: 'Ada Okonkwo',
    maxBid: '$2,800',
    current: '$2,400',
    t30: '45m',
    status: 'Active',
    source: 'BidBridge',
    auctionLot: 'iPhone 14 Pro pallet (24 units)',
    increment: '$20',
    created: '17 Aug 2026, 08:00',
    ends: '17 Aug 2026, 21:00',
    history: [hist('Proxy armed', '17 Aug 2026, 08:00', 'Active')],
  },
  {
    id: 'PRX-3312',
    lot: 'Lot #3312',
    buyer: 'Bola Shittu',
    maxBid: '$1,900',
    current: '$1,840',
    t30: 'Ended',
    status: 'Winning',
    source: 'BidBridge',
    auctionLot: 'Gaming console mixed lot #3312',
    increment: '$20',
    created: '15 Aug 2026, 09:00',
    ends: '15 Aug 2026, 21:30',
    history: [hist('Winning at close', '15 Aug 2026, 21:30', 'Winning')],
  },
  {
    id: 'PRX-1190',
    lot: 'Lot #1190',
    buyer: 'Chidi Madueke',
    maxBid: '$740',
    current: '$810',
    t30: 'Ended',
    status: 'Outbid',
    source: 'BidBridge',
    auctionLot: 'Refurbished laptop case lot',
    increment: '$15',
    created: '14 Aug 2026, 10:00',
    ends: '14 Aug 2026, 19:12',
    history: [hist('Outbid', '14 Aug 2026, 19:12', 'Outbid')],
  },
]

export const ADMIN_WITHDRAWALS: AdminWithdrawal[] = [
  {
    id: 'WDR-331',
    buyer: 'Chidi Madueke',
    amount: '$500',
    requested: '16 Aug 2026, 16:55',
    status: 'Pending',
    destination: 'GTB · ****4412',
    method: 'Bank transfer',
    history: [hist('Requested', '16 Aug 2026, 16:55', 'Pending')],
    notes: [],
  },
  {
    id: 'WDR-330',
    buyer: 'Funmi Adeyemi',
    amount: '$120',
    requested: '15 Aug 2026, 10:20',
    status: 'Pending',
    destination: 'Access · ****2291',
    method: 'Bank transfer',
    history: [hist('Requested', '15 Aug 2026, 10:20', 'Pending')],
    notes: [],
  },
  {
    id: 'WDR-322',
    buyer: 'Ada Okonkwo',
    amount: '$250',
    requested: '10 Aug 2026, 08:02',
    status: 'Completed',
    destination: 'Zenith · ****8810',
    method: 'Bank transfer',
    history: [hist('Approved', '10 Aug 2026, 09:15', 'Approved'), hist('Paid out', '10 Aug 2026, 11:40', 'Completed')],
    notes: [],
  },
  {
    id: 'WDR-318',
    buyer: 'Kunle Fashola',
    amount: '$80',
    requested: '8 Aug 2026, 14:11',
    status: 'Rejected',
    destination: 'UBA · ****1002',
    method: 'Bank transfer',
    history: [hist('Rejected', '8 Aug 2026, 16:00', 'Rejected', 'Name mismatch on account')],
    notes: [],
  },
]

export const ADMIN_TPL: AdminTplCheck[] = [
  {
    id: 'TPL-810',
    orderId: 'ORD-810',
    buyer: 'Amaka Eze',
    device: 'iPhone 13 Pro 256GB',
    imei: '356938035643809',
    serial: 'F2LXC0X0Q6L4',
    status: 'Failed',
    submitted: '15 Aug 2026, 09:12',
    history: [hist('Phonecheck failed', '15 Aug 2026, 09:12', 'Failed', 'Device blacklisted')],
  },
  {
    id: 'TPL-655',
    orderId: 'ORD-655',
    buyer: 'Funmi Adeyemi',
    device: 'Pixel 8 128GB',
    imei: '353247103928110',
    serial: '8A2K91L0Q',
    status: 'Verified',
    submitted: '12 Aug 2026, 08:10',
    history: [hist('Verified at US 3PL', '12 Aug 2026, 08:10', 'Verified')],
  },
  {
    id: 'TPL-702',
    orderId: 'ORD-702',
    buyer: 'Emeka Terver',
    device: 'Galaxy S24 Ultra',
    imei: '358240051111110',
    serial: 'R5CT90K',
    status: 'Pending',
    submitted: '17 Aug 2026, 07:44',
    history: [hist('Awaiting IMEI transcription', '17 Aug 2026, 07:44', 'Pending')],
  },
]

export const ADMIN_TICKETS: AdminTicket[] = [
  {
    id: 'TCK-2041',
    buyer: 'Bola Shittu',
    subject: 'Settlement window expired unfairly',
    category: 'Settlement',
    priority: 'Urgent',
    sla: 'Breached',
    status: 'Open',
    assignee: 'Unassigned',
    opened: '16 Aug 2026, 10:02',
    lastReply: '16 Aug 2026, 10:02',
    created: '16 Aug 2026, 10:02',
    updated: '16 Aug 2026, 10:02',
    messages: [
      { from: 'Bola Shittu', at: '16 Aug 2026, 10:02', body: 'The 12h window closed while I was transferring funds. Please reopen settlement for lot #3312.' },
    ],
    notes: [],
  },
  {
    id: 'TCK-2038',
    buyer: 'Ada Okonkwo',
    subject: 'Need invoice for freight credit',
    category: 'Billing',
    priority: 'Normal',
    sla: '6h left',
    status: 'Open',
    assignee: 'Ops Admin',
    opened: '17 Aug 2026, 08:15',
    lastReply: '17 Aug 2026, 09:40',
    created: '17 Aug 2026, 08:15',
    updated: '17 Aug 2026, 09:40',
    messages: [
      { from: 'Ada Okonkwo', at: '17 Aug 2026, 08:15', body: 'Can you send a PDF of last month’s freight credits?' },
      { from: 'Ops Admin', at: '17 Aug 2026, 09:40', body: 'Pulling this now — you’ll have it within the hour.' },
    ],
    notes: [],
  },
  {
    id: 'TCK-2010',
    buyer: 'Chidi Madueke',
    subject: 'Withdrawal destination change',
    category: 'Wallet',
    priority: 'Normal',
    sla: 'Resolved',
    status: 'Resolved',
    assignee: 'Ops Admin',
    opened: '9 Aug 2026, 12:00',
    lastReply: '9 Aug 2026, 15:22',
    created: '9 Aug 2026, 12:00',
    updated: '9 Aug 2026, 15:22',
    messages: [{ from: 'Ops Admin', at: '9 Aug 2026, 15:22', body: 'Destination updated. You can request payout again.' }],
    notes: [],
  },
  {
    id: 'TCK-1994',
    buyer: 'Kunle Fashola',
    subject: 'Cannot upload KYC photo',
    category: 'Verification',
    priority: 'Low',
    sla: 'Closed',
    status: 'Closed',
    assignee: 'Ops Admin',
    opened: '2 Aug 2026, 11:11',
    lastReply: '3 Aug 2026, 09:00',
    created: '2 Aug 2026, 11:11',
    updated: '3 Aug 2026, 09:00',
    messages: [{ from: 'Ops Admin', at: '3 Aug 2026, 09:00', body: 'Upload limit raised. Closing this ticket.' }],
    notes: [],
  },
]

export const ADMIN_BUYERS: AdminBuyer[] = [
  {
    id: 'BYR-1008',
    name: 'Ada Okonkwo',
    email: 'ada.okonkwo@example.com',
    phone: '+234 802 555 0192',
    type: 'Individual',
    kyc: 'Verified',
    tier: 'Tier 2',
    status: 'Active',
    wallet: '$1,240',
    joined: '2 Jun 2026',
    address: '19 Bourdillon Road, Ikoyi',
    notes: [],
  },
  {
    id: 'BYR-1004',
    name: 'Chidi Madueke',
    email: 'chidi.madueke@example.com',
    phone: '+234 803 221 6677',
    type: 'Individual',
    kyc: 'Verified',
    tier: 'Tier 1',
    status: 'Active',
    wallet: '$860',
    joined: '1 Mar 2026',
    address: '44 Awolowo Road, Ikoyi',
    notes: [],
  },
  {
    id: 'BYR-1019',
    name: 'Bola Shittu',
    email: 'bola.shittu@example.com',
    phone: '+234 809 112 8844',
    type: 'Individual',
    kyc: 'Pending',
    tier: 'Tier 1',
    status: 'Restricted',
    wallet: '$40',
    joined: '15 Aug 2026',
    address: '21 Allen Avenue, Ikeja',
    notes: [],
  },
  {
    id: 'BYR-1022',
    name: 'Ngozi Balogun',
    email: 'ngozi.balogun@example.com',
    phone: '+234 802 114 5567',
    type: 'Business',
    kyc: 'Pending',
    tier: 'Tier 1',
    status: 'Active',
    wallet: '$0',
    joined: '17 Aug 2026',
    company: 'Balogun Trading Co.',
    address: '14 Adeola Odeku St, Lagos',
    notes: [],
  },
  {
    id: 'BYR-0991',
    name: 'Amaka Eze',
    email: 'amaka.eze@example.com',
    phone: '+234 701 990 4410',
    type: 'Individual',
    kyc: 'Verified',
    tier: 'Tier 2',
    status: 'Deactivated',
    wallet: '$0',
    joined: '11 Jan 2026',
    address: '3 Akin Adesola, VI',
    notes: [note('n2', 'Deactivated after blacklisted device on ORD-810.', '15 Aug 2026, 12:00')],
  },
  {
    id: 'BYR-1001',
    name: 'Funmi Adeyemi',
    email: 'funmi.adeyemi@example.com',
    phone: '+234 805 333 2210',
    type: 'Individual',
    kyc: 'Verified',
    tier: 'Tier 3',
    status: 'Active',
    wallet: '$2,110',
    joined: '4 Nov 2025',
    address: '9 Gerrard Road, Ikoyi',
    notes: [],
  },
  {
    id: 'BYR-1011',
    name: 'Emeka Terver',
    email: 'emeka.terver@example.com',
    phone: '+234 806 778 1200',
    type: 'Individual',
    kyc: 'Verified',
    tier: 'Tier 2',
    status: 'Active',
    wallet: '$540',
    joined: '22 Apr 2026',
    address: '18 Karimu Kotun, VI',
    notes: [],
  },
  {
    id: 'BYR-0988',
    name: 'Kunle Fashola',
    email: 'kunle.fashola@example.com',
    phone: '+234 809 004 1188',
    type: 'Individual',
    kyc: 'Requires Resubmission',
    tier: 'Tier 1',
    status: 'Active',
    wallet: '$15',
    joined: '28 Jul 2026',
    address: '2 Oba Akran, Ikeja',
    notes: [],
  },
]

export const ADMIN_REGULATION: AdminRegulation[] = [
  {
    id: 'REG-1008',
    buyer: 'Ada Okonkwo',
    flags: ['PEP watch — cleared'],
    status: 'Active',
    lastReview: '3 Jun 2026',
    reason: 'Standard KYC',
    history: [hist('Cleared', '3 Jun 2026', 'Active')],
  },
  {
    id: 'REG-1019',
    buyer: 'Bola Shittu',
    flags: ['Payment default', 'Settlement overdue'],
    status: 'Restricted',
    lastReview: '16 Aug 2026',
    reason: 'Missed 12h settlement on lot #3312',
    history: [hist('Restricted', '16 Aug 2026, 09:44', 'Restricted')],
  },
  {
    id: 'REG-0991',
    buyer: 'Amaka Eze',
    flags: ['Blacklisted device'],
    status: 'Deactivated',
    lastReview: '15 Aug 2026',
    reason: 'Phonecheck blacklist on ORD-810',
    history: [hist('Deactivated', '15 Aug 2026, 12:00', 'Deactivated')],
  },
  {
    id: 'REG-0880',
    buyer: 'Tunde Bakare',
    flags: ['Repeated KYC failure'],
    status: 'Suspended',
    lastReview: '12 Feb 2026',
    reason: 'Did not resubmit documents',
    history: [hist('Suspended', '12 Feb 2026', 'Suspended')],
  },
]

export const ADMIN_AUCTIONS: AdminAuction[] = [
  {
    id: 'AUC-4412',
    title: 'Wednesday wholesale — electronics',
    product: 'iPhone 14 Pro pallet (24 units)',
    lots: 18,
    starts: '17 Aug 2026, 09:00',
    ends: '17 Aug 2026, 21:00',
    status: 'Live',
    bids: 14,
    gmv: '$48,200',
    currentBid: '$1,840',
    highestBidder: 'Ada Okonkwo',
    bidHold: '$2,000',
  },
  {
    id: 'AUC-219',
    title: 'Tuesday mixed pallet',
    product: 'Gaming console mixed lot #3312',
    lots: 12,
    starts: '16 Aug 2026, 09:00',
    ends: '16 Aug 2026, 21:00',
    status: 'Ended',
    bids: 40,
    gmv: '$31,400',
    currentBid: '$1,840',
    highestBidder: 'Bola Shittu',
    bidHold: '—',
  },
  {
    id: 'AUC-221',
    title: 'Thursday flower & edibles',
    product: '2 Oz Deal Watermelon Zkittles + Purple Gushers',
    lots: 22,
    starts: '18 Aug 2026, 09:00',
    ends: '18 Aug 2026, 21:00',
    status: 'Upcoming',
    bids: 0,
    gmv: '—',
    currentBid: '$2,500',
    highestBidder: '—',
    bidHold: '—',
  },
]

export const ADMIN_LOTS: AdminLot[] = [
  { id: 'L-7001', title: '2 Oz Deal Watermelon Zkittles + Purple Gushers', category: 'Flower', status: 'Published', currentBid: '$2,500', source: 'SYNC-88213', published: '16 Aug 2026', condition: 'Customer Returns | Used Fair', location: 'Bothel, WA' },
  { id: 'L-7002', title: 'Full Spectrum CBD Tincture 1000mg — 24-Unit Case', category: 'Edibles', status: 'Published', currentBid: '$2,550', source: 'SYNC-88213', published: '16 Aug 2026', condition: 'New', location: 'Bothel, WA' },
  { id: 'L-3312', title: 'Gaming console mixed lot #3312', category: 'Electronics', status: 'Ended', currentBid: '$1,840', source: 'Manual', published: '14 Aug 2026', condition: 'Used Fair', location: 'Dallas, TX' },
  { id: 'L-8821', title: 'BidBridge mixed pallet #8821', category: 'Electronics', status: 'Live', currentBid: '$2,400', source: 'BidBridge', published: '17 Aug 2026', condition: 'Mixed', location: 'Ontario, CA' },
]

export const ADMIN_ORDERS: AdminOrder[] = [
  {
    id: 'ORD-810',
    buyer: 'Amaka Eze',
    lot: 'iPhone 13 Pro 256GB',
    total: '$640',
    status: '3PL Failed',
    placed: '14 Aug 2026',
    fulfillment: 'US 3PL',
    history: [hist('Placed', '14 Aug 2026', 'Completed'), hist('3PL failed', '15 Aug 2026', 'Failed')],
  },
  {
    id: 'ORD-655',
    buyer: 'Funmi Adeyemi',
    lot: 'Pixel 8 128GB',
    total: '$410',
    status: 'Delivered',
    placed: '8 Aug 2026',
    fulfillment: 'US 3PL',
    history: [hist('Verified at 3PL', '12 Aug 2026', 'Verified'), hist('Delivered', '14 Aug 2026', 'Delivered')],
  },
  {
    id: 'ORD-702',
    buyer: 'Emeka Terver',
    lot: 'Galaxy S24 Ultra',
    total: '$890',
    status: 'Customs',
    placed: '15 Aug 2026',
    fulfillment: 'Customs',
    history: [hist('In transit', '16 Aug 2026', 'Processing'), hist('Arrived customs', '17 Aug 2026', 'Processing')],
  },
  {
    id: 'ORD-688',
    buyer: 'Ada Okonkwo',
    lot: 'CBD case lot',
    total: '$1,120',
    status: 'In transit',
    placed: '13 Aug 2026',
    fulfillment: 'US 3PL',
    history: [hist('Shipped', '14 Aug 2026', 'Processing')],
  },
]

export const ADMIN_SHIPMENTS: AdminShipment[] = [
  {
    id: 'SHP-655',
    orderId: 'ORD-655',
    buyer: 'Funmi Adeyemi',
    carrier: 'UPS',
    tracking: '1Z999AA10123456784',
    status: 'Delivered',
    eta: '14 Aug 2026',
    origin: 'Ontario, CA',
    destination: 'Lagos, NG',
    history: [hist('Delivered', '14 Aug 2026, 11:02', 'Delivered')],
  },
  {
    id: 'SHP-702',
    orderId: 'ORD-702',
    buyer: 'Emeka Terver',
    carrier: 'DHL',
    tracking: 'JD0146000039281',
    status: 'Customs Clearance',
    eta: '19 Aug 2026',
    origin: 'Dallas, TX',
    destination: 'Abuja, NG',
    history: [hist('Arrived destination customs', '17 Aug 2026, 06:10', 'Processing')],
  },
  {
    id: 'SHP-688',
    orderId: 'ORD-688',
    buyer: 'Ada Okonkwo',
    carrier: 'FedEx',
    tracking: '794644119870',
    status: 'In Transit',
    eta: '20 Aug 2026',
    origin: 'Bothel, WA',
    destination: 'Lagos, NG',
    history: [hist('Departed origin', '14 Aug 2026', 'Processing')],
  },
]

export const ADMIN_TRANSACTIONS: AdminTransaction[] = [
  {
    id: 'TXN-9102',
    buyer: 'Ada Okonkwo',
    type: 'Deposit',
    amount: '+$500',
    status: 'Credited',
    at: '17 Aug 2026, 08:02',
    method: 'USDC',
    reference: 'Circle',
    history: [hist('Credited', '17 Aug 2026, 08:02', 'Completed')],
  },
  {
    id: 'TXN-9098',
    buyer: 'Ada Okonkwo',
    type: 'Bid hold',
    amount: '-$2,400',
    status: 'Locked',
    at: '17 Aug 2026, 04:40',
    method: 'Wallet',
    reference: 'Lot #8821',
    history: [hist('Hold placed', '17 Aug 2026, 04:40', 'Processing')],
  },
  {
    id: 'TXN-9080',
    buyer: 'Bola Shittu',
    type: 'Settlement charge',
    amount: '-$1,430',
    status: 'Completed',
    at: '15 Aug 2026, 21:32',
    method: 'Wallet',
    reference: 'Lot #3312',
    history: [hist('Charged', '15 Aug 2026, 21:32', 'Completed')],
  },
  {
    id: 'TXN-9001',
    buyer: 'Chidi Madueke',
    type: 'Withdrawal',
    amount: '-$500',
    status: 'Pending',
    at: '16 Aug 2026, 16:55',
    method: 'Bank transfer',
    reference: 'WDR-331',
    history: [hist('Requested', '16 Aug 2026, 16:55', 'Pending')],
  },
]

export const ADMIN_REFERRALS: AdminReferral[] = [
  { id: 'REF-01', referrer: 'Ada Okonkwo', buyer: 'Chidi Madueke', code: 'ADA-REF01', qualification: 'Rewarded', reward: '$20 wallet credit', date: '12 Mar 2026' },
  { id: 'REF-02', referrer: 'Ada Okonkwo', buyer: 'Bola Shittu', code: 'ADA-REF02', qualification: 'Qualified', reward: '$20 wallet credit', date: '16 Aug 2026' },
  { id: 'REF-03', referrer: 'Ada Okonkwo', buyer: 'Emeka Terver', code: 'ADA-REF03', qualification: 'Pending', reward: '—', date: '22 Apr 2026' },
  { id: 'REF-04', referrer: 'Kunle Fashola', buyer: 'New user #905', code: 'KUNLE-3', qualification: 'Pending', reward: '—', date: '28 Jul 2026' },
  { id: 'REF-05', referrer: 'Emeka Terver', buyer: 'New user #882', code: 'EMEKA-7', qualification: 'Pending', reward: '—', date: '1 Aug 2026' },
]

export const ADMIN_FEES: AdminFee[] = [
  { id: 'fee-bstock', name: 'B-Stock markup', value: '8%', appliesTo: 'BidBridge lots', lastChanged: '4 Aug 2026', changedBy: 'Ops Admin' },
  { id: 'fee-hold', name: 'Bid hold', value: '100% of max bid', appliesTo: 'All live auctions', lastChanged: '12 Jul 2026', changedBy: 'Ops Admin' },
  { id: 'fee-premium', name: 'Buyer premium', value: '8%', appliesTo: 'Winning bids', lastChanged: '12 Jul 2026', changedBy: 'Ops Admin' },
  { id: 'fee-withdrawal', name: 'Withdrawal fee', value: '$2.50', appliesTo: 'Bank payouts', lastChanged: '1 Jun 2026', changedBy: 'Ops Admin' },
]

export const ADMIN_TIERS: AdminTier[] = [
  { id: 'tier-1', name: 'Tier 1', hold: '100%', limit: '$2,500 / lot', buyers: 48, lastChanged: '12 Jul 2026' },
  { id: 'tier-2', name: 'Tier 2', hold: '50%', limit: '$10,000 / lot', buyers: 22, lastChanged: '17 Aug 2026' },
  { id: 'tier-3', name: 'Tier 3', hold: '25%', limit: '$25,000 / lot', buyers: 7, lastChanged: '1 Jun 2026' },
]

export const ADMIN_SYNCS: AdminSyncJob[] = [
  { id: 'SYNC-88213', source: 'BidBridge', started: '17 Aug 2026, 06:00', finished: '17 Aug 2026, 06:14', status: 'Published', lots: 18, failed: 0 },
  { id: 'SYNC-88210', source: 'BidBridge', started: '16 Aug 2026, 06:00', finished: '16 Aug 2026, 06:22', status: 'Failed items', lots: 12, failed: 2 },
  { id: 'SYNC-88190', source: 'Manual CSV', started: '14 Aug 2026, 11:40', finished: '14 Aug 2026, 11:41', status: 'Published', lots: 4, failed: 0 },
]

export const ADMIN_AUDIT: AdminAuditEntry[] = [
  { id: 'AUD-10452', action: 'Buyer tier overridden', actor: 'Ops Admin', target: 'Ada Okonkwo', at: '17 Aug 2026, 14:10', ip: '102.89.23.14' },
  { id: 'AUD-10451', action: 'KYC verification approved', actor: 'Ops Admin', target: 'Emeka Terver', at: '17 Aug 2026, 08:31', ip: '102.89.23.14' },
  { id: 'AUD-10440', action: 'Settlement marked default', actor: 'Ops Admin', target: 'Bola Shittu', at: '16 Aug 2026, 09:44', ip: '102.89.23.14' },
  { id: 'AUD-10422', action: 'Admin user created', actor: 'Ops Admin', target: 'Zainab Musa', at: '12 Aug 2026, 10:02', ip: '102.89.23.14' },
]

export const ADMIN_USERS: AdminUserRecord[] = [
  { id: 'ADM-01', name: 'Ops Admin', email: 'ops@vskglobal.com', role: 'Administrator', status: 'Active', lastActive: '17 Aug 2026, 14:10', created: '1 Jan 2026' },
  { id: 'ADM-02', name: 'Zainab Musa', email: 'zainab.musa@vskglobal.com', role: 'Administrator', status: 'Active', lastActive: '17 Aug 2026, 09:02', created: '12 Aug 2026' },
  { id: 'ADM-03', name: 'Tunde Bakare', email: 'tunde.bakare@vskglobal.com', role: 'Administrator', status: 'Suspended', lastActive: '2 Feb 2026, 16:11', created: '4 Jan 2026' },
  { id: 'ADM-04', name: 'Ibrahim Sule', email: 'ibrahim.sule@vskglobal.com', role: 'Administrator', status: 'Active', lastActive: '16 Aug 2026, 18:40', created: '20 Mar 2026' },
  { id: 'ADM-05', name: 'Kemi Adewale', email: 'kemi.adewale@vskglobal.com', role: 'Administrator', status: 'Deactivated', lastActive: '11 May 2026, 12:00', created: '11 May 2026' },
]

export const ADMIN_ANALYTICS: AdminAnalyticsTab[] = [
  {
    id: 'growth',
    label: 'Growth',
    subtitle: 'Buyer growth, KYC progress, tier progression, and referral performance.',
    kpis: [
      { label: 'New buyers (30d)', value: '186', hint: '+18% vs prior 30d', hintTone: 'success' },
      { label: 'KYC pass rate', value: '91%', hint: 'of submitted reviews' },
      { label: 'Tier upgrades', value: '12', hint: 'last 30 days' },
      { label: 'Referral signups', value: '42', hint: 'last 30 days' },
    ],
    panels: [
      {
        type: 'line',
        title: 'Buyer growth — last 8 weeks',
        points: [
          { label: 'W1', value: 42 },
          { label: 'W2', value: 48 },
          { label: 'W3', value: 45 },
          { label: 'W4', value: 55 },
          { label: 'W5', value: 58 },
          { label: 'W6', value: 52 },
          { label: 'W7', value: 61 },
          { label: 'W8', value: 66 },
        ],
      },
      {
        type: 'donut',
        title: 'KYC status distribution',
        slices: [
          { label: 'Approved', value: 82, color: '#047857' },
          { label: 'Pending', value: 12, color: '#d97706' },
          { label: 'Rejected', value: 4, color: '#dc2626' },
          { label: 'Resubmission', value: 3, color: '#94a3b8' },
        ],
      },
      {
        type: 'bar',
        title: 'Buyers by tier',
        points: [
          { label: 'Tier 1', value: 620 },
          { label: 'Tier 2', value: 290 },
          { label: 'Tier 3', value: 98 },
        ],
      },
      {
        type: 'funnel',
        title: 'Referral funnel',
        funnel: [
          { stage: 'Signups', count: 42, conversion: '100%' },
          { stage: 'Qualified', count: 31, conversion: '74%' },
          { stage: 'Rewarded', count: 26, conversion: '62%' },
        ],
      },
    ],
    headers: ['BUYER', 'SOURCE', 'KYC', 'JOINED'],
    rows: [
      { a: 'Ngozi Balogun', b: 'Organic', c: 'Pending', d: '17 Aug' },
      { a: 'Bola Shittu', b: 'Referral · Ada', c: 'Pending', d: '15 Aug' },
      { a: 'Ifeoma Nwosu', b: 'Organic', c: 'Rejected', d: '16 Aug' },
    ],
  },
  {
    id: 'marketplace',
    label: 'Marketplace',
    subtitle: "Live auction activity, what's selling, and B-Stock sync health.",
    kpis: [
      { label: 'Live lots', value: '64', hint: 'on platform' },
      { label: 'GMV (7d)', value: '$128k', hint: 'hammer price' },
      { label: 'Sell-through', value: '71%', hint: 'ended lots' },
      { label: 'Avg bids / lot', value: '8.4', hint: 'last 30d' },
    ],
    panels: [
      {
        type: 'bar',
        title: 'GMV · last 7 days',
        points: [
          { label: 'Mon', value: 40 },
          { label: 'Tue', value: 62 },
          { label: 'Wed', value: 55 },
          { label: 'Thur', value: 88 },
          { label: 'Fri', value: 70 },
          { label: 'Sat', value: 48 },
          { label: 'Sun', value: 30 },
        ],
      },
      {
        type: 'line',
        title: 'Lots ending · last 7 days',
        points: [
          { label: 'Mon', value: 8 },
          { label: 'Tue', value: 12 },
          { label: 'Wed', value: 10 },
          { label: 'Thur', value: 15 },
          { label: 'Fri', value: 14 },
          { label: 'Sat', value: 6 },
          { label: 'Sun', value: 4 },
        ],
      },
    ],
    headers: ['LOT', 'CATEGORY', 'BIDS', 'CURRENT'],
    rows: [
      { a: 'L-8821', b: 'Electronics', c: '14', d: '$2,400' },
      { a: 'L-7001', b: 'Flower', c: '40', d: '$2,500' },
      { a: 'L-7002', b: 'Edibles', c: '40', d: '$2,550' },
    ],
  },
  {
    id: 'bidding',
    label: 'Bidding',
    subtitle: 'Bid volume, proxy placement, and outbid patterns.',
    kpis: [
      { label: 'Active bidders', value: '86', hint: 'last 7 days' },
      { label: 'Proxy bids', value: '12', hint: 'BidBridge' },
      { label: 'Outbid rate', value: '34%', hint: 'ended lots' },
      { label: 'Avg max bid', value: '$1,120', hint: 'last 30d' },
    ],
    panels: [
      {
        type: 'bar',
        title: 'Bids placed · last 7 days',
        points: [
          { label: 'Mon', value: 30 },
          { label: 'Tue', value: 80 },
          { label: 'Wed', value: 50 },
          { label: 'Thur', value: 90 },
          { label: 'Fri', value: 85 },
          { label: 'Sat', value: 60 },
          { label: 'Sun', value: 35 },
        ],
      },
      {
        type: 'line',
        title: 'Proxy wins · last 7 days',
        points: [
          { label: 'Mon', value: 2 },
          { label: 'Tue', value: 4 },
          { label: 'Wed', value: 3 },
          { label: 'Thur', value: 5 },
          { label: 'Fri', value: 4 },
          { label: 'Sat', value: 2 },
          { label: 'Sun', value: 1 },
        ],
      },
    ],
    headers: ['BUYER', 'LOT', 'MAX BID', 'STATUS'],
    rows: [
      { a: 'Ada Okonkwo', b: 'L-8821', c: '$2,800', d: 'Active' },
      { a: 'Bola Shittu', b: 'L-3312', c: '$1,900', d: 'Winning' },
      { a: 'Chidi Madueke', b: 'L-1190', c: '$740', d: 'Outbid' },
    ],
  },
  {
    id: 'money',
    label: 'Money',
    subtitle: 'Deposits, holds, withdrawals, and wallet balance trends.',
    kpis: [
      { label: 'Deposits', value: '$42.1k', hint: 'this week' },
      { label: 'Holds', value: '$18.4k', hint: 'locked' },
      { label: 'Withdrawals', value: '$6.2k', hint: 'requested' },
      { label: 'Net wallet', value: '$91k', hint: 'platform' },
    ],
    panels: [
      {
        type: 'bar',
        title: 'Deposits vs withdrawals',
        points: [
          { label: 'Mon', value: 22 },
          { label: 'Tue', value: 73 },
          { label: 'Wed', value: 44 },
          { label: 'Thur', value: 72 },
          { label: 'Fri', value: 77 },
          { label: 'Sat', value: 73 },
          { label: 'Sun', value: 51 },
        ],
      },
      {
        type: 'line',
        title: 'Net wallet balance',
        points: [
          { label: 'Mon', value: 82 },
          { label: 'Tue', value: 84 },
          { label: 'Wed', value: 86 },
          { label: 'Thur', value: 88 },
          { label: 'Fri', value: 90 },
          { label: 'Sat', value: 91 },
          { label: 'Sun', value: 91 },
        ],
      },
    ],
    headers: ['TXN', 'BUYER', 'TYPE', 'AMOUNT'],
    rows: [
      { a: 'TXN-9102', b: 'Ada Okonkwo', c: 'Deposit', d: '+$500' },
      { a: 'TXN-9098', b: 'Ada Okonkwo', c: 'Bid hold', d: '-$2,400' },
      { a: 'TXN-9001', b: 'Chidi Madueke', c: 'Withdrawal', d: '-$500' },
    ],
  },
  {
    id: 'settlement',
    label: 'Settlement',
    subtitle: 'Collection rates, overdue risk, and time-to-pay.',
    kpis: [
      { label: 'Due now', value: '3', hint: 'inside 12h', hintTone: 'warning' },
      { label: 'Overdue', value: '1', hint: 'default risk', hintTone: 'danger' },
      { label: 'Collected', value: '$38k', hint: 'this week' },
      { label: 'Avg time', value: '4.2h', hint: 'to pay' },
    ],
    panels: [
      {
        type: 'bar',
        title: 'Settlements collected',
        points: [
          { label: 'Mon', value: 50 },
          { label: 'Tue', value: 40 },
          { label: 'Wed', value: 70 },
          { label: 'Thur', value: 90 },
          { label: 'Fri', value: 65 },
          { label: 'Sat', value: 20 },
          { label: 'Sun', value: 10 },
        ],
      },
      {
        type: 'donut',
        title: 'Settlement status',
        slices: [
          { label: 'Completed', value: 68, color: '#047857' },
          { label: 'Pending', value: 22, color: '#d97706' },
          { label: 'Overdue', value: 10, color: '#dc2626' },
        ],
      },
    ],
    headers: ['SETTLEMENT', 'BUYER', 'REMAINING', 'STATUS'],
    rows: [
      { a: 'SET-3312', b: 'Bola Shittu', c: '$410', d: 'Overdue' },
      { a: 'SET-8821', b: 'Ada Okonkwo', c: '$600', d: 'Pending' },
      { a: 'SET-4410', b: 'Emeka Terver', c: '$0', d: 'Completed' },
    ],
  },
  {
    id: 'procurement',
    label: 'Procurement',
    subtitle: 'Lot ingestion, sync health, and source performance.',
    kpis: [
      { label: 'Sources live', value: '3', hint: 'BidBridge + CSV' },
      { label: 'Lots ingested', value: '34', hint: 'this week' },
      { label: 'Failed items', value: '2', hint: 'need publish', hintTone: 'warning' },
      { label: 'Markup', value: '8%', hint: 'B-Stock' },
    ],
    panels: [
      {
        type: 'bar',
        title: 'Lots ingested',
        points: [
          { label: 'Mon', value: 18 },
          { label: 'Tue', value: 12 },
          { label: 'Wed', value: 18 },
          { label: 'Thur', value: 9 },
          { label: 'Fri', value: 14 },
          { label: 'Sat', value: 4 },
          { label: 'Sun', value: 2 },
        ],
      },
      {
        type: 'donut',
        title: 'Sync outcomes',
        slices: [
          { label: 'Published', value: 78, color: '#047857' },
          { label: 'Failed items', value: 14, color: '#dc2626' },
          { label: 'Skipped', value: 8, color: '#94a3b8' },
        ],
      },
    ],
    headers: ['SYNC', 'SOURCE', 'LOTS', 'STATUS'],
    rows: [
      { a: 'SYNC-88213', b: 'BidBridge', c: '18', d: 'Published' },
      { a: 'SYNC-88210', b: 'BidBridge', c: '12', d: 'Failed items' },
      { a: 'SYNC-88190', b: 'Manual CSV', c: '4', d: 'Published' },
    ],
  },
  {
    id: 'logistics',
    label: 'Logistics',
    subtitle: 'Shipment pipeline, customs holds, and 3PL queue.',
    kpis: [
      { label: 'In transit', value: '9', hint: 'active' },
      { label: 'Customs', value: '3', hint: 'held', hintTone: 'warning' },
      { label: 'Delivered (7d)', value: '14', hint: 'completed' },
      { label: '3PL queue', value: '3', hint: 'IMEI checks' },
    ],
    panels: [
      {
        type: 'bar',
        title: 'Shipments by status',
        points: [
          { label: 'Mon', value: 20 },
          { label: 'Tue', value: 35 },
          { label: 'Wed', value: 28 },
          { label: 'Thur', value: 40 },
          { label: 'Fri', value: 38 },
          { label: 'Sat', value: 22 },
          { label: 'Sun', value: 12 },
        ],
      },
      {
        type: 'donut',
        title: 'Shipment status mix',
        slices: [
          { label: 'In transit', value: 45, color: '#1d4ed8' },
          { label: 'Customs', value: 18, color: '#d97706' },
          { label: 'Delivered', value: 37, color: '#047857' },
        ],
      },
    ],
    headers: ['SHIPMENT', 'ORDER', 'STATUS', 'ETA'],
    rows: [
      { a: 'SHP-702', b: 'ORD-702', c: 'Customs Clearance', d: '19 Aug' },
      { a: 'SHP-688', b: 'ORD-688', c: 'In Transit', d: '20 Aug' },
      { a: 'SHP-655', b: 'ORD-655', c: 'Delivered', d: '14 Aug' },
    ],
  },
  {
    id: 'support',
    label: 'Support',
    subtitle: 'Ticket volume, SLA performance, and CSAT.',
    kpis: [
      { label: 'Open tickets', value: '7', hint: 'queue' },
      { label: 'SLA breached', value: '1', hint: 'needs owner', hintTone: 'danger' },
      { label: 'Median first reply', value: '42m', hint: 'this week' },
      { label: 'CSAT', value: '4.6', hint: 'last 30d' },
    ],
    panels: [
      {
        type: 'bar',
        title: 'Tickets opened',
        points: [
          { label: 'Mon', value: 8 },
          { label: 'Tue', value: 12 },
          { label: 'Wed', value: 6 },
          { label: 'Thur', value: 10 },
          { label: 'Fri', value: 9 },
          { label: 'Sat', value: 3 },
          { label: 'Sun', value: 2 },
        ],
      },
      {
        type: 'line',
        title: 'Median first reply (mins)',
        points: [
          { label: 'Mon', value: 52 },
          { label: 'Tue', value: 48 },
          { label: 'Wed', value: 44 },
          { label: 'Thur', value: 42 },
          { label: 'Fri', value: 40 },
          { label: 'Sat', value: 55 },
          { label: 'Sun', value: 60 },
        ],
      },
    ],
    headers: ['TICKET', 'BUYER', 'PRIORITY', 'STATUS'],
    rows: [
      { a: 'TCK-2041', b: 'Bola Shittu', c: 'Urgent', d: 'Open' },
      { a: 'TCK-2038', b: 'Ada Okonkwo', c: 'Normal', d: 'Open' },
      { a: 'TCK-2010', b: 'Chidi Madueke', c: 'Normal', d: 'Resolved' },
    ],
  },
  {
    id: 'revenue',
    label: 'Revenue',
    subtitle: 'Take rate, fee streams, and month-over-month trends.',
    kpis: [
      { label: 'Buyer premium', value: '$9,440', hint: 'this month' },
      { label: 'B-Stock markup', value: '$3,120', hint: 'this month' },
      { label: 'Withdrawal fees', value: '$42.50', hint: 'this month' },
      { label: 'Net take', value: '$12.6k', hint: 'this month' },
    ],
    panels: [
      {
        type: 'bar',
        title: 'Take rate · last 7 days',
        points: [
          { label: 'Mon', value: 35 },
          { label: 'Tue', value: 50 },
          { label: 'Wed', value: 48 },
          { label: 'Thur', value: 80 },
          { label: 'Fri', value: 70 },
          { label: 'Sat', value: 40 },
          { label: 'Sun', value: 22 },
        ],
      },
      {
        type: 'donut',
        title: 'Revenue mix',
        slices: [
          { label: 'Buyer premium', value: 62, color: '#531424' },
          { label: 'B-Stock markup', value: 28, color: '#835561' },
          { label: 'Withdrawal fees', value: 10, color: '#94a3b8' },
        ],
      },
    ],
    headers: ['STREAM', 'THIS WEEK', 'THIS MONTH', 'TREND'],
    rows: [
      { a: 'Buyer premium', b: '$2,180', c: '$9,440', d: '+12%' },
      { a: 'B-Stock markup', b: '$740', c: '$3,120', d: '+4%' },
      { a: 'Withdrawal fees', b: '$12.50', c: '$42.50', d: 'flat' },
    ],
  },
]
