import lotGummies from '@/assets/images/lot-gummies.png'
import type { Lot, Offer, Order, WalletTx, NotificationItem, NotificationPrefs, Dispute, Contract, User, SupportTicket, ReferralContact, ReferralReward } from '@/types'

export const DEMO_USER: User = {
  id: 'u1',
  name: 'Chukwuemeka Adeyemi',
  email: 'c.adeyemi@northbridgetrading.ng',
  role: 'user',
  company: 'Northbridge Trading Ltd',
  phone: '+234 803 221 4456',
  tier: 2,
  kycStatus: 'verified',
  kybStatus: 'pending',
  avatarInitials: 'CA',
}

const daysFromNow = (d: number) => new Date(Date.now() + d * 86400000).toISOString()
const hoursFromNow = (h: number) => new Date(Date.now() + h * 3600000).toISOString()
const minutesFromNow = (m: number) => new Date(Date.now() + m * 60000).toISOString()

export const CATEGORIES = [
  { name: 'Shop All', slug: 'all', dropdown: false },
  { name: 'Flower', slug: 'flower', dropdown: true },
  { name: 'Edibles', slug: 'edibles', dropdown: false },
  { name: 'Concentrates', slug: 'concentrates', dropdown: true },
  { name: 'Mushrooms', slug: 'mushrooms', dropdown: false },
  { name: 'Promotions/Bundles', slug: 'promotions', dropdown: true },
  { name: 'Support', slug: 'support', dropdown: true },
  { name: 'Rewards', slug: 'rewards', dropdown: false },
  { name: 'Blog', slug: 'blog', dropdown: false },
] as const

export const LOTS: Lot[] = [
  {
    id: 'lot-1',
    slug: 'watermelon-zkittles-deal',
    title: '2 Oz Deal Watermelon Zkittles + Purple Gushers',
    subtitle: '24 units across 3 SKUs — 8 units each of three flavors',
    category: 'Flower',
    categorySlug: 'flower',
    image: lotGummies,
    location: 'Bothel, WA',
    condition: 'Customer Returns | Used Fair',
    currentBid: 2500,
    bidCount: 40,
    msrp: 3264,
    units: 100,
    endsAt: minutesFromNow(138),
    status: 'live',
    dockVerified: true,
    buyerPremiumPct: 8,
    description:
      '24 units across a verified lot. Built from this lot’s manifest — verify before bid. Buyer arranges freight. Seller ships FOB origin.',
    brand: 'PureCBD Co.',
    tags: ['Bulk', 'Pallet', 'Dock Verified'],
  },
  {
    id: 'lot-2',
    slug: 'cbd-tincture-24-unit',
    title: 'Full Spectrum CBD Tincture 1000mg — 24-Unit Case',
    subtitle: '30 ml glass dropper bottle, broad-spectrum oil base',
    category: 'Edibles',
    categorySlug: 'edibles',
    image: lotGummies,
    location: 'Bothel, WA',
    condition: 'Customer Returns | Used Fair',
    currentBid: 2550,
    bidCount: 40,
    msrp: 3264,
    units: 100,
    endsAt: hoursFromNow(17),
    status: 'live',
    dockVerified: true,
    buyerPremiumPct: 8,
    description: 'Bulk pallet lot with mixed SKUs. All bids are binding.',
    brand: 'GreenLeaf Naturals',
    tags: ['CBD', 'Case'],
  },
  {
    id: 'lot-3',
    slug: 'cat-320d-excavator',
    title: 'Caterpillar 320D Hydraulic Excavator',
    subtitle: 'Commercial heavy equipment · inspection complete',
    category: 'Concentrates',
    categorySlug: 'concentrates',
    image: lotGummies,
    location: 'Houston, TX',
    condition: 'Used — Good',
    currentBid: 64500,
    bidCount: 27,
    msrp: 120000,
    units: 1,
    endsAt: minutesFromNow(43),
    status: 'live',
    dockVerified: false,
    buyerPremiumPct: 10,
    description: 'Phonecheck-style inspection complete. Full payment due within 48 hours of close.',
    brand: 'Caterpillar',
    tags: ['Excavator', 'Heavy'],
  },
  {
    id: 'lot-4',
    slug: 'iphone-13-pallet',
    title: 'Pallet — 50x Apple iPhone 14 (Grade B)',
    subtitle: 'Grade B refurbished · carrier unlocked mix',
    category: 'Electronics',
    categorySlug: 'mushrooms',
    image: lotGummies,
    location: 'Delaware, US',
    condition: 'Refurbished Grade A',
    currentBid: 18200,
    bidCount: 41,
    msrp: 49500,
    units: 180,
    endsAt: daysFromNow(-2),
    status: 'ended',
    dockVerified: true,
    buyerPremiumPct: 8,
    description: 'Inspection & Phonecheck verification complete.',
    brand: 'Apple',
    tags: ['Phones', 'Pallet'],
  },
  {
    id: 'lot-5',
    slug: 'perkins-500kva',
    title: 'Generator Set — 500kVA Perkins',
    subtitle: 'Industrial power · export ready',
    category: 'Concentrates',
    categorySlug: 'concentrates',
    image: lotGummies,
    location: 'Lagos, NG',
    condition: 'New surplus',
    currentBid: 22680,
    bidCount: 19,
    msrp: 61300,
    units: 1,
    endsAt: daysFromNow(-3),
    status: 'ended',
    dockVerified: true,
    buyerPremiumPct: 8,
    description: 'Export documentation available. Buyer arranges freight.',
    brand: 'Perkins',
    tags: ['Generator'],
  },
  {
    id: 'lot-6',
    slug: 'actros-1845',
    title: 'Mercedes-Benz Actros 1845 Tractor Unit',
    subtitle: 'Commercial vehicle · EU fleet surplus',
    category: 'Promotions/Bundles',
    categorySlug: 'promotions',
    image: lotGummies,
    location: 'Rotterdam, NL',
    condition: 'Used — Excellent',
    currentBid: 39900,
    bidCount: 19,
    msrp: 70000,
    units: 1,
    endsAt: minutesFromNow(8),
    status: 'live',
    dockVerified: false,
    buyerPremiumPct: 8,
    description: 'Fleet Auctions EU surplus unit.',
    brand: 'Mercedes-Benz',
    tags: ['Truck'],
  },
  {
    id: 'lot-7',
    slug: 'komatsu-pc210',
    title: 'Truckload — John Deere Riding Mowers x12',
    subtitle: 'Mid-size excavator · hours verified',
    category: 'Concentrates',
    categorySlug: 'concentrates',
    image: lotGummies,
    location: 'Abuja, NG',
    condition: 'Used — Fair',
    currentBid: 34500,
    bidCount: 12,
    msrp: 65000,
    units: 1,
    endsAt: daysFromNow(-8),
    status: 'ended',
    dockVerified: true,
    buyerPremiumPct: 10,
    description: 'Hours and service history included in manifest.',
    brand: 'John Deere',
    tags: ['Mower'],
  },
  {
    id: 'lot-8',
    slug: 'citrus-burst-case',
    title: 'Citrus Burst Nutraceutical Case Pack',
    subtitle: '1000 mg / 30 ml · 24 units',
    category: 'Edibles',
    categorySlug: 'edibles',
    image: lotGummies,
    location: 'Bothel, WA',
    condition: 'New / factory sealed',
    currentBid: 20742,
    bidCount: 22,
    msrp: 56000,
    units: 24,
    endsAt: daysFromNow(-4),
    status: 'ended',
    dockVerified: true,
    buyerPremiumPct: 8,
    description: 'Category: Health & Wellness · Nutraceuticals.',
    brand: 'NatureWell',
    tags: ['Case'],
  },
  {
    id: 'lot-9',
    slug: 'dyson-v15-pallet',
    title: 'Pallet — 80x Dyson V15 Detect Vacuums',
    subtitle: 'Customer returns · tested mix',
    category: 'Electronics',
    categorySlug: 'edibles',
    image: lotGummies,
    location: 'Delaware, US',
    condition: 'Refurbished',
    currentBid: 10400,
    bidCount: 18,
    msrp: 28000,
    units: 80,
    endsAt: daysFromNow(-10),
    status: 'ended',
    dockVerified: true,
    buyerPremiumPct: 8,
    description: 'Mixed grade returns. Buyer arranges freight.',
    brand: 'Dyson',
    tags: ['Pallet'],
  },
]

export const INITIAL_BIDS = [
  { id: 'b1', lotId: 'lot-1', amount: 2500, status: 'leading' as const, placedAt: daysFromNow(-1), maxBid: 3200 },
  { id: 'b2', lotId: 'lot-2', amount: 2400, status: 'outbid' as const, placedAt: daysFromNow(-2), maxBid: 2500 },
  { id: 'b3', lotId: 'lot-3', amount: 64500, status: 'leading' as const, placedAt: daysFromNow(-0.5), maxBid: 70000 },
  { id: 'b4', lotId: 'lot-6', amount: 38500, status: 'outbid' as const, placedAt: daysFromNow(-1), maxBid: 40000 },
  {
    id: 'b5',
    lotId: 'lot-4',
    amount: 18200,
    status: 'won' as const,
    placedAt: daysFromNow(-2),
    maxBid: 18200,
    settlementDueAt: hoursFromNow(11.7),
  },
  {
    id: 'b6',
    lotId: 'lot-5',
    amount: 22680,
    status: 'won' as const,
    placedAt: daysFromNow(-3),
    maxBid: 22680,
    settlementDueAt: hoursFromNow(18),
  },
  {
    id: 'b7',
    lotId: 'lot-8',
    amount: 20742,
    status: 'won' as const,
    placedAt: daysFromNow(-4),
    maxBid: 20742,
    settlementDueAt: hoursFromNow(30),
  },
  {
    id: 'b8',
    lotId: 'lot-7',
    amount: 31000,
    status: 'lost' as const,
    placedAt: daysFromNow(-8),
    maxBid: 31000,
    winningBid: 34500,
  },
  {
    id: 'b9',
    lotId: 'lot-9',
    amount: 9800,
    status: 'lost' as const,
    placedAt: daysFromNow(-10),
    maxBid: 9800,
    winningBid: 10400,
  },
]


export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'o1',
    lotId: 'lot-6',
    direction: 'received',
    amount: 48000,
    listPrice: 52320,
    status: 'pending',
    counterparty: 'GlobalTech Buyers',
    createdAt: daysFromNow(-2),
    expiresAt: daysFromNow(1),
    note: 'We can settle immediately via wire.',
  },
  {
    id: 'o2',
    lotId: 'lot-3',
    direction: 'received',
    amount: 62000,
    listPrice: 70000,
    status: 'pending',
    counterparty: 'HeavyEquip NG',
    createdAt: daysFromNow(-1),
    expiresAt: daysFromNow(2),
    note: 'Inspection reports attached. Ready to close this week.',
  },
  {
    id: 'o3',
    lotId: 'lot-1',
    direction: 'sent',
    amount: 2300,
    listPrice: 2500,
    status: 'countered',
    counterparty: 'PureCBD Co.',
    createdAt: daysFromNow(-3),
    expiresAt: daysFromNow(1),
    note: 'Counter at list less 8%.',
  },
  {
    id: 'o4',
    lotId: 'lot-5',
    direction: 'sent',
    amount: 22680,
    listPrice: 61300,
    status: 'accepted',
    counterparty: 'BuildMat Imports',
    createdAt: daysFromNow(-6),
    expiresAt: daysFromNow(-1),
  },
  {
    id: 'o5',
    lotId: 'lot-2',
    direction: 'received',
    amount: 2100,
    listPrice: 2550,
    status: 'declined',
    counterparty: 'GreenLeaf Naturals',
    createdAt: daysFromNow(-8),
    expiresAt: daysFromNow(-5),
  },
  {
    id: 'o6',
    lotId: 'lot-4',
    direction: 'sent',
    amount: 16500,
    listPrice: 18200,
    status: 'expired',
    counterparty: 'Fleet Auctions EU',
    createdAt: daysFromNow(-12),
    expiresAt: daysFromNow(-4),
  },
]

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-3391',
    lotId: 'lot-3',
    status: 'in_transit',
    amount: 74200,
    placedAt: '2026-07-18T10:00:00.000Z',
    eta: '19 Aug 2026',
    seller: 'Costco Wholesale',
    progress: 57,
    checkpointDone: 4,
    checkpointTotal: 7,
    steps: [
      { label: 'Auction Won & Deposit Secured', done: true, at: '18 Jul' },
      { label: 'Balance Payment Settled', done: true, at: '18 Jul' },
      { label: 'Seller Dispatched to US Dock', done: true, at: '21 Jul' },
      { label: 'Arrived at Delaware Receiving Dock', done: true, at: '27 Jul' },
      { label: 'Inspection & Phonecheck Verification Complete', done: false, current: true, at: 'In progress' },
      { label: 'Export Documentation & Compliance Prep', done: false, at: 'Est. 17 Aug' },
      { label: 'International Freight Transit', done: false, at: 'Est. 17 Aug' },
      { label: 'Destination Customs Clearance Processing', done: false, at: 'Est. 17 Aug' },
      { label: 'Last-Mile Courier Handover', done: false, at: 'Est. 17 Aug' },
      { label: 'Successfully Delivered to Buyer', done: false, at: 'Est. 19 Aug' },
    ],
  },
  {
    id: 'ORD-3402',
    lotId: 'lot-4',
    status: 'awaiting_payment',
    amount: 61300,
    placedAt: daysFromNow(-2),
    eta: '17 Aug 2026',
    seller: 'Apple Surplus',
    progress: 14,
    checkpointDone: 1,
    checkpointTotal: 7,
    steps: [
      { label: 'Auction Won & Deposit Secured', done: true, at: '21 Aug' },
      { label: 'Awaiting Payment', done: false, current: true, at: 'In progress' },
      { label: 'Balance Payment Settled', done: false, at: 'Est. 24 Aug' },
      { label: 'Seller Dispatched to US Dock', done: false, at: 'Est. 26 Aug' },
      { label: 'Inspection & Phonecheck Verification Complete', done: false, at: 'Est. 28 Aug' },
      { label: 'International Freight Transit', done: false, at: 'Est. 4 Sep' },
      { label: 'Successfully Delivered to Buyer', done: false, at: 'Est. 12 Sep' },
    ],
  },
  {
    id: 'ORD-3288',
    lotId: 'lot-6',
    status: 'delivered',
    amount: 28900,
    placedAt: daysFromNow(-40),
    eta: '12 Jul 2026',
    seller: 'BuildMat Imports',
    progress: 100,
    checkpointDone: 7,
    checkpointTotal: 7,
    steps: [
      { label: 'Auction Won & Deposit Secured', done: true, at: '2 Jun' },
      { label: 'Balance Payment Settled', done: true, at: '3 Jun' },
      { label: 'Seller Dispatched to US Dock', done: true, at: '6 Jun' },
      { label: 'Arrived at Delaware Receiving Dock', done: true, at: '14 Jun' },
      { label: 'Inspection & Phonecheck Verification Complete', done: true, at: '16 Jun' },
      { label: 'International Freight Transit', done: true, at: '28 Jun' },
      { label: 'Successfully Delivered to Buyer', done: true, at: '12 Jul' },
    ],
  },
  {
    id: 'ORD-3355',
    lotId: 'lot-5',
    status: 'customs',
    amount: 41500,
    placedAt: daysFromNow(-22),
    eta: '28 Aug 2026',
    seller: 'Perkins Power',
    progress: 71,
    checkpointDone: 5,
    checkpointTotal: 7,
    steps: [
      { label: 'Auction Won & Deposit Secured', done: true, at: '1 Aug' },
      { label: 'Balance Payment Settled', done: true, at: '2 Aug' },
      { label: 'Seller Dispatched to US Dock', done: true, at: '5 Aug' },
      { label: 'Arrived at Delaware Receiving Dock', done: true, at: '12 Aug' },
      { label: 'Inspection & Phonecheck Verification Complete', done: true, at: '14 Aug' },
      { label: 'Destination Customs Clearance Processing', done: false, current: true, at: 'In progress' },
      { label: 'Last-Mile Courier Handover', done: false, at: 'Est. 26 Aug' },
      { label: 'Successfully Delivered to Buyer', done: false, at: 'Est. 28 Aug' },
    ],
  },
]

export const INITIAL_WALLET_TX: WalletTx[] = [
  {
    id: 't1',
    type: 'deposit',
    amount: 25000,
    asset: 'USDT (TRC20)',
    status: 'completed',
    date: 'Aug 2',
    label: 'Deposit',
    detail: 'TR7Nh…9k2a',
  },
  {
    id: 't2',
    type: 'escrow_hold',
    amount: -8200,
    asset: 'USD',
    status: 'completed',
    date: 'Aug 1',
    label: 'Escrow hold',
    detail: 'ORD-3391',
  },
  {
    id: 't3',
    type: 'deposit',
    amount: 41240,
    asset: 'USDC (ERC20)',
    status: 'completed',
    date: 'Jul 30',
    label: 'Deposit',
    detail: '0x8a3f…c21b',
  },
  {
    id: 't4',
    type: 'withdrawal',
    amount: -14200,
    asset: 'BTC',
    status: 'completed',
    date: 'Jul 28',
    label: 'Withdrawal',
    detail: 'bc1q…7m2',
  },
  {
    id: 't5',
    type: 'fee',
    amount: -453,
    asset: 'USD',
    status: 'completed',
    date: 'Jul 27',
    label: 'Platform fee',
    detail: 'Buyer premium',
  },
  {
    id: 't6',
    type: 'refund',
    amount: 1240,
    asset: 'USD',
    status: 'pending',
    date: 'Jul 26',
    label: 'Refund',
    detail: 'ORD-3288',
  },
  {
    id: 't7',
    type: 'escrow_release',
    amount: 5600,
    asset: 'USD',
    status: 'completed',
    date: 'Jul 24',
    label: 'Escrow release',
    detail: 'ORD-3102',
  },
  {
    id: 't8',
    type: 'withdrawal',
    amount: -36578.4,
    asset: 'USDC (ERC20)',
    status: 'completed',
    date: 'Jul 21',
    label: 'Withdrawal',
    detail: '0x4c1e…91af',
  },
  {
    id: 't9',
    type: 'deposit',
    amount: 15000,
    asset: 'USD',
    status: 'completed',
    date: 'Jul 18',
    label: 'Wire deposit',
    detail: 'ACH · ****4421',
  },
]

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    title: "You've been outbid on LOT-4755",
    body: 'Current bid $39,900. Your max was $39,100.',
    read: false,
    createdAt: minutesFromNow(-6),
    type: 'bid',
    actionLabel: 'Bid again →',
    actionTo: '/lots/lot-6',
  },
  {
    id: 'n2',
    title: 'Payment due for ORD-3402',
    body: '$61,300 due within 22 hours to keep your win.',
    read: false,
    createdAt: hoursFromNow(-1),
    type: 'order',
    actionLabel: 'Pay now →',
    actionTo: '/orders?order=ORD-3402',
  },
  {
    id: 'n3',
    title: 'Deposit confirmed',
    body: '25,000 USDT credited to your wallet.',
    read: true,
    createdAt: hoursFromNow(-3),
    type: 'wallet',
    actionLabel: 'View wallet →',
    actionTo: '/wallet',
  },
  {
    id: 'n4',
    title: 'Anti-sniping extension',
    body: 'LOT-4821 extended by 3 minutes after a late bid.',
    read: true,
    createdAt: hoursFromNow(-5),
    type: 'auction',
    actionLabel: 'View lot →',
    actionTo: '/lots/lot-1',
  },
  {
    id: 'n5',
    title: 'KYB review in progress',
    body: 'Your business documents are under review (2–3 business days).',
    read: true,
    createdAt: daysFromNow(-1),
    type: 'account',
    actionLabel: 'View status →',
    actionTo: '/verification',
  },
  {
    id: 'n6',
    title: "You're leading on LOT-4790",
    body: 'Your bid of $52,320 is currently the highest. Closes soon.',
    read: true,
    createdAt: daysFromNow(-1),
    type: 'bid',
    actionLabel: 'View lot →',
    actionTo: '/lots/lot-3',
  },
  {
    id: 'n7',
    title: 'Shipment dispatched — ORD-3288',
    body: 'Your order has been picked up by the freight carrier.',
    read: true,
    createdAt: daysFromNow(-3),
    type: 'order',
    actionLabel: 'Track order →',
    actionTo: '/orders?order=ORD-3288',
  },
  {
    id: 'n8',
    title: 'Withdrawal processed',
    body: '−$8,500 BTC withdrawal completed successfully.',
    read: true,
    createdAt: daysFromNow(-4),
    type: 'wallet',
  },
  {
    id: 'n9',
    title: 'Auction closing soon — LOT-4888',
    body: 'This watched lot closes in under 1 hour. Current bid $18,200.',
    read: true,
    createdAt: daysFromNow(-5),
    type: 'auction',
    actionLabel: 'Bid now →',
    actionTo: '/lots/lot-4',
  },
]

export const INITIAL_NOTIFICATION_PREFS: NotificationPrefs = {
  outbidAlerts: true,
  auctionEndingSoon: true,
  paymentDue: true,
  shipmentUpdates: true,
  walletActivity: true,
}

export const INITIAL_DISPUTES: Dispute[] = [
  {
    id: 'DSP-1041',
    orderId: 'ORD-3355',
    lotId: 'lot-5',
    status: 'under_review',
    reason: 'Item not as described',
    details:
      'The generator arrived with a broken control panel and scuffed housing that was not disclosed in the listing.',
    amount: 41500,
    openedAt: '2026-08-03T09:14:00.000Z',
    updatedAt: '2026-08-07T10:00:00.000Z',
    completedSteps: 2,
    events: [
      {
        actor: 'you',
        title: 'Dispute opened',
        at: '3 Aug 09:14',
        body: 'The generator arrived with a broken control panel and scuffed housing that was not disclosed in the listing.',
      },
      {
        actor: 'system',
        title: 'Evidence requested',
        at: '3 Aug 09:15',
        body: 'Please upload photos of the item as received and a copy of the original listing.',
      },
      {
        actor: 'you',
        title: 'Evidence submitted',
        at: '4 Aug 14:30',
        body: 'Uploaded 6 photos and the original listing screenshot.',
      },
      {
        actor: 'cs',
        title: 'Under review',
        at: '5 Aug 10:00',
        body: 'Your evidence has been received. Our team is reviewing the case with the seller.',
      },
    ],
  },
  {
    id: 'DSP-1028',
    orderId: 'ORD-3288',
    lotId: 'lot-6',
    status: 'resolved',
    reason: 'Significant delivery delay',
    details: 'Shipment arrived well past the quoted ETA with no proactive update from the seller.',
    amount: 28900,
    openedAt: '2026-07-12T11:00:00.000Z',
    updatedAt: '2026-07-22T16:40:00.000Z',
    completedSteps: 4,
    events: [
      {
        actor: 'you',
        title: 'Dispute opened',
        at: '12 Jul 11:00',
        body: 'Shipment arrived well past the quoted ETA with no proactive update from the seller.',
      },
      {
        actor: 'cs',
        title: 'Resolved',
        at: '22 Jul 16:40',
        body: 'Seller issued a freight credit. This dispute is closed.',
      },
    ],
  },
  {
    id: 'DSP-1052',
    orderId: 'ORD-3402',
    lotId: 'lot-4',
    status: 'awaiting_response',
    reason: 'Payment dispute — double charge',
    details: 'Wallet was charged twice for the same settlement on this order.',
    amount: 61300,
    openedAt: '2026-08-18T08:22:00.000Z',
    updatedAt: '2026-08-18T08:22:00.000Z',
    completedSteps: 1,
    events: [
      {
        actor: 'you',
        title: 'Dispute opened',
        at: '18 Aug 08:22',
        body: 'Wallet was charged twice for the same settlement on this order.',
      },
      {
        actor: 'system',
        title: 'Evidence requested',
        at: '18 Aug 08:23',
        body: 'Please upload a screenshot of both charges from your wallet activity.',
      },
    ],
  },
]

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'c1',
    contractNumber: 'CNT-2024-0441',
    orderId: 'ORD-3391',
    lotId: 'lot-3',
    title: 'Purchase Agreement — Komatsu PC210 Excavator',
    status: 'active',
    counterparty: 'ClearWater Heavy Plant',
    updatedAt: daysFromNow(-5),
    contractDate: daysFromNow(-30),
    effectiveDate: daysFromNow(-30),
    expirationDate: daysFromNow(335),
    parties: [
      {
        name: 'Northbridge Trading Ltd',
        role: 'Buyer',
        initials: 'NT',
        signed: true,
        signedAt: daysFromNow(-29),
      },
      {
        name: 'ClearWater Heavy Plant',
        role: 'Seller',
        initials: 'CW',
        signed: true,
        signedAt: daysFromNow(-28),
      },
    ],
    terms: [
      'Purchase price of $74,200 is payable within 48 hours of contract activation.',
      'Title transfers to buyer upon cleared settlement and escrow release.',
      'Seller warrants the lot matches the published manifest within stated variances.',
      'Jurisdiction: Nigeria · Disputes follow VSK Global arbitration rules.',
    ],
    documents: [
      { name: 'Purchase-Agreement-CNT-2024-0441.pdf', size: '284 KB' },
      { name: 'Lot-Manifest-LOT-4703.pdf', size: '128 KB' },
      { name: 'Escrow-Release-Instructions.pdf', size: '96 KB' },
    ],
    activity: [
      { label: 'Contract created from won auction ORD-3391', at: daysFromNow(-30) },
      { label: 'Buyer signed — Northbridge Trading Ltd', at: daysFromNow(-29) },
      { label: 'Seller signed — contract active', at: daysFromNow(-28) },
    ],
  },
  {
    id: 'c2',
    contractNumber: 'CNT-2024-0512',
    orderId: 'ORD-3402',
    lotId: 'lot-6',
    title: 'Purchase Agreement — Mercedes-Benz Actros 1845',
    status: 'awaiting_signature',
    counterparty: 'Fleet Auctions EU',
    updatedAt: daysFromNow(-1),
    contractDate: daysFromNow(-2),
    effectiveDate: daysFromNow(-2),
    expirationDate: daysFromNow(363),
    parties: [
      {
        name: 'Northbridge Trading Ltd',
        role: 'Buyer',
        initials: 'NT',
        signed: false,
      },
      {
        name: 'Fleet Auctions EU',
        role: 'Seller',
        initials: 'FA',
        signed: true,
        signedAt: daysFromNow(-1),
      },
    ],
    terms: [
      'Purchase price of $39,900 is payable within 48 hours of contract activation.',
      'Buyer arranges export freight from Rotterdam within 14 days of title transfer.',
      'Seller provides EU roadworthiness documentation package.',
      'Jurisdiction: Netherlands · Escrow held until dock verification.',
    ],
    documents: [
      { name: 'Purchase-Agreement-CNT-2024-0512.pdf', size: '256 KB' },
      { name: 'Vehicle-Inspection-Report.pdf', size: '412 KB' },
    ],
    activity: [
      { label: 'Contract created from won auction ORD-3402', at: daysFromNow(-2) },
      { label: 'Seller signed — awaiting buyer signature', at: daysFromNow(-1) },
    ],
  },
  {
    id: 'c3',
    contractNumber: 'CNT-2024-0388',
    orderId: 'ORD-3288',
    lotId: 'lot-5',
    title: 'Purchase Agreement — Generator Set 500kVA Perkins',
    status: 'completed',
    counterparty: 'BuildMat Imports',
    updatedAt: daysFromNow(-40),
    contractDate: daysFromNow(-60),
    effectiveDate: daysFromNow(-60),
    expirationDate: daysFromNow(-20),
    parties: [
      {
        name: 'Northbridge Trading Ltd',
        role: 'Buyer',
        initials: 'NT',
        signed: true,
        signedAt: daysFromNow(-59),
      },
      {
        name: 'BuildMat Imports',
        role: 'Seller',
        initials: 'BI',
        signed: true,
        signedAt: daysFromNow(-58),
      },
    ],
    terms: [
      'Purchase price of $22,680 settled in full via escrow.',
      'Goods delivered and accepted at Lagos receiving dock.',
      'Warranty period of 90 days from delivery for latent defects.',
      'Jurisdiction: Nigeria · Contract closed after delivery confirmation.',
    ],
    documents: [
      { name: 'Purchase-Agreement-CNT-2024-0388.pdf', size: '271 KB' },
      { name: 'Delivery-Confirmation.pdf', size: '84 KB' },
      { name: 'Final-Settlement-Receipt.pdf', size: '62 KB' },
    ],
    activity: [
      { label: 'Contract created from won auction ORD-3288', at: daysFromNow(-60) },
      { label: 'Buyer signed', at: daysFromNow(-59) },
      { label: 'Seller signed — contract active', at: daysFromNow(-58) },
      { label: 'Delivery confirmed — contract completed', at: daysFromNow(-20) },
    ],
  },
  {
    id: 'c4',
    contractNumber: 'CNT-2024-0601',
    orderId: 'ORD-3510',
    lotId: 'lot-1',
    title: 'Purchase Agreement — Watermelon Zkittles Bundle',
    status: 'draft',
    counterparty: 'PureCBD Co.',
    updatedAt: daysFromNow(0),
    contractDate: daysFromNow(0),
    effectiveDate: daysFromNow(0),
    expirationDate: daysFromNow(365),
    parties: [
      {
        name: 'Northbridge Trading Ltd',
        role: 'Buyer',
        initials: 'NT',
        signed: false,
      },
      {
        name: 'PureCBD Co.',
        role: 'Seller',
        initials: 'PC',
        signed: false,
      },
    ],
    terms: [
      'Draft terms pending legal review before circulation to parties.',
      'Purchase price and freight schedule to be confirmed.',
      'Manifest variance tolerance set at 2% by unit count.',
      'Jurisdiction: United States · Washington State law.',
    ],
    documents: [{ name: 'Draft-Agreement-CNT-2024-0601.pdf', size: '118 KB' }],
    activity: [{ label: 'Draft contract generated', at: daysFromNow(0) }],
  },
]

export const TICKET_CATEGORIES = [
  'Orders & shipping',
  'Bidding & settlement',
  'Wallet & escrow',
  'Verification',
] as const

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-2291',
    subject: 'Customs document rejected for ORD-3355',
    category: 'Orders & shipping',
    status: 'awaiting_you',
    updatedAt: hoursFromNow(-2),
    messages: [
      {
        from: 'you',
        body: 'Customs flagged our PAAR document. What format do you need?',
        at: 'Yesterday 14:02',
      },
      {
        from: 'agent',
        body: 'Please upload the stamped PAAR as PDF, plus the Form M number. We’ll re-submit within 24h.',
        at: 'Today 09:41',
      },
    ],
  },
  {
    id: 'TCK-2270',
    subject: 'Withdrawal to BTC address pending',
    category: 'Wallet & escrow',
    status: 'open',
    updatedAt: daysFromNow(-1),
    messages: [
      {
        from: 'you',
        body: 'I initiated a BTC withdrawal yesterday and it is still showing pending.',
        at: 'Yesterday 11:20',
      },
      {
        from: 'agent',
        body: 'Network confirmations are in progress. We’ll notify you as soon as the transfer broadcasts.',
        at: 'Yesterday 12:04',
      },
    ],
  },
  {
    id: 'TCK-2188',
    subject: 'Add second delivery address',
    category: 'Orders & shipping',
    status: 'resolved',
    updatedAt: daysFromNow(-6),
    messages: [
      {
        from: 'you',
        body: 'Can we split delivery of ORD-3288 across two warehouse addresses?',
        at: '17 Aug 09:12',
      },
      {
        from: 'agent',
        body: 'Second address added to the file. Last-mile courier has been updated.',
        at: '17 Aug 16:40',
      },
    ],
  },
]

export const REFERRAL_CODE = 'CHUKWU2024'
export const REFERRAL_LINK = `https://vskglobal/ref/${REFERRAL_CODE}`
export const REFERRAL_CREDIT = 50
export const REFERRAL_SUMMARY = {
  earned: 150,
  used: 50,
  available: 100,
}

export const INITIAL_REFERRALS: ReferralContact[] = [
  {
    id: 'r1',
    name: 'Kemi Okafor',
    company: 'Tech Ventures NG',
    initials: 'KO',
    email: 'kemi@techventures.ng',
    invitedAt: 'Jul 28, 2026',
    status: 'reward_earned',
    reward: 50,
  },
  {
    id: 'r2',
    name: 'Taiwo Adebisi',
    company: 'Fast Goods Ltd',
    initials: 'TA',
    email: 't.adebisi@fastgoods.ng',
    invitedAt: 'Jul 15, 2026',
    status: 'reward_earned',
    reward: 50,
  },
  {
    id: 'r3',
    name: 'Seun Bello',
    company: 'Global Imports Co.',
    initials: 'SB',
    email: 's.bello@globalimports.ng',
    invitedAt: 'Jul 3, 2026',
    status: 'reward_earned',
    reward: 50,
  },
  {
    id: 'r4',
    name: 'Adaeze Nwosu',
    company: 'TradePlus NG',
    initials: 'AN',
    email: 'a.nwosu@tradeplus.ng',
    invitedAt: 'Aug 9, 2026',
    status: 'pending_verification',
    reward: null,
  },
  {
    id: 'r5',
    name: 'Musa Aliyu',
    company: 'Northern Trade NG',
    initials: 'MA',
    email: 'm.aliyu@northerntrade.ng',
    invitedAt: 'Aug 9, 2026',
    status: 'pending_verification',
    reward: null,
  },
]

export const INITIAL_REFERRAL_REWARDS: ReferralReward[] = [
  { id: 'rw1', name: 'Seun Bello', company: 'Global Imports Co.', date: 'Jul 10, 2026', amount: 50 },
  { id: 'rw2', name: 'Taiwo Adebisi', company: 'Fast Goods Ltd', date: 'Jul 22, 2026', amount: 50 },
  { id: 'rw3', name: 'Kemi Okafor', company: 'Tech Ventures NG', date: 'Aug 5, 2026', amount: 50 },
]

export function canonicalLotId(id: string) {
  return id.replace(/-(?:slide|pad)-\d+/g, '')
}

export function getLot(id: string) {
  const direct = LOTS.find((l) => l.id === id || l.slug === id)
  if (direct) return direct
  // Carousel / grid clones append "-slide-N" or "-pad-N"
  const baseId = canonicalLotId(id)
  if (baseId !== id) return LOTS.find((l) => l.id === baseId || l.slug === baseId)
  return undefined
}
